---
- name: Setup Docker environment and deploy monitoring stack
  hosts: devops-instance
  become: yes

  tasks:
    - name: Update apt and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker CE and docker-compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-compose
        state: present

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Copy docker-compose.yml to VM
      copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy prometheus.yml to VM
      copy:
        src: prometheus.yml
        dest: /home/ubuntu/prometheus.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Create loki directory if not exists
      file:
        path: /home/ubuntu/loki
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy Loki config.yaml to VM
      copy:
        src: ./loki/config.yml
        dest: /home/ubuntu/loki/config.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Set correct permissions for Loki config
      become: true
      ansible.builtin.command: chown -R 10001:10001 /home/ubuntu/loki

    - name: Create promtail directory if not exists
      file:
        path: /home/ubuntu/promtail
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy Promtail config.yaml to VM
      copy:
        src: ./promtail/config.yml
        dest: /home/ubuntu/promtail/config.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Launch monitoring stack with docker-compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu

    - name: Wait for Grafana port 3000 to be open
      wait_for:
        port: 3000
        timeout: 30
