name: Deploy Infrastructure and Configuration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Create terraform.tfvars with secrets
        working-directory: ./terraform-aws
        run: |
          echo 'public_key = "${{ secrets.SSH_PUBLIC_KEY }}"' > terraform.tfvars

      - name: Terraform Init and Apply
        working-directory: ./terraform-aws
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip sshpass
          pip3 install ansible

      - name: Generate Ansible inventory
        working-directory: ./terraform-aws
        run: |
          chmod +x ./generate_inventory.sh
          ./generate_inventory.sh

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory setup-docker.yml --ssh-extra-args="-o StrictHostKeyChecking=no"
